# Generated by Django 6.1 on 2026-09-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='experience',
            name='category',
            field=models.CharField(default='volunteer', max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='ended_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='started_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
