# Generated by Django 5.2.17 on 2026-09-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_experience_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
