# Generated by Django 5.2.17 on 2026-09-18 14:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_project_project_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='started_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
